import { describe, expect, test } from 'bun:test'

import {
  FIELD_OPTION_GRID_CLASS,
  FIELD_OPTION_TILE_BODY_CLASS,
  FIELD_OPTION_TILE_CAPTION_CLASS,
  FIELD_OPTION_TILE_CLASS,
  FIELD_OPTION_TILE_DISABLED_CLASS,
  FIELD_OPTION_TILE_ICON_CLASS,
  FIELD_OPTION_TILE_INTERACTIVE_CLASS,
  FIELD_OPTION_TILE_LABEL_CLASS,
  FIELD_OPTION_TILE_PLACEHOLDER_CLASS,
  FIELD_OPTION_TILE_ROW_CLASS,
  FIELD_OPTION_TILE_SELECTED_CLASS,
  FIELD_OPTION_TILE_SIGNAL_CLASS
} from './field-option-classes'

describe('field option class names', () => {
  test('use shared field-option prefix for settings option tiles', () => {
    for (const className of [
      FIELD_OPTION_GRID_CLASS,
      FIELD_OPTION_TILE_CLASS,
      FIELD_OPTION_TILE_INTERACTIVE_CLASS,
      FIELD_OPTION_TILE_SELECTED_CLASS,
      FIELD_OPTION_TILE_DISABLED_CLASS,
      FIELD_OPTION_TILE_PLACEHOLDER_CLASS,
      FIELD_OPTION_TILE_ROW_CLASS,
      FIELD_OPTION_TILE_ICON_CLASS,
      FIELD_OPTION_TILE_BODY_CLASS,
      FIELD_OPTION_TILE_SIGNAL_CLASS,
      FIELD_OPTION_TILE_LABEL_CLASS,
      FIELD_OPTION_TILE_CAPTION_CLASS
    ]) {
      expect(className.startsWith('field-option-')).toBe(true)
    }
  })
})
