minimum_version: 2.11.0

service: <%= ENV['SERVICE'] %>

servers:
  web:
    hosts:
      - <%= ENV['IP'] %>
    options:
      device:
        - /dev/kvm

registry:
  server: localhost:5555

ssh:
  port: <%= ENV['SSH_PORT'] %>

volumes:
  - "datastores:/app/datastores/"

proxy:
  ssl: true
  app_port: 3000
  response_timeout: 600
  host: <%= ENV['HOST'] %>
  buffering:
    responses: false

builder:
  arch: amd64

env:
  clear:
    SERVICE: <%= ENV['SERVICE'] %>
  secret:
    - AI_TYPE
    - AI_MODEL
    - AI_API_KEY
    - AI_BASE_URL
    - AUTH_SECRET
    - AUTH_BEARER
    - AUTH_PASSWORD
    - WEBHOOK_KEY_1
    - WEBHOOK_KEY_2
    - WEBHOOK_KEY_3
    - IP
