minimum_version: 2.11.0

service: pierre

servers:
  web:
    hosts:
      - <%= ENV['IP'] %>
    options:
      device:
        - /dev/kvm

registry:
  server: localhost:5555

ssh:
  port: <%= ENV['SSH_PORT'] %>

volumes:
  - 'datastores:/app/datastores/'

proxy:
  ssl: true
  forward_headers: true
  app_port: 3000
  response_timeout: 600
  host: <%= ENV['HOST'] %>
  buffering:
    responses: false

deploy_timeout: 300

builder:
  arch: amd64

env:
  secret:
    - AI_TYPE
    - AI_MODEL
    - AI_API_KEY
    - AI_BASE_URL
    - AUTH_SECRET
    - AUTH_BEARER
    - AUTH_PASSWORD
    - CM_PRODUCT_TOKEN
    - CM_FROM
    - CM_WEBHOOK_SECRET
    - IP
